### ISSUE TITLE
Edge of overmap space bounces you

### ISSUE THREAD

**Issue by SpagootyEggant** [BeeStation/NSV13#1896] opened 2022-04-23 01:51 UTC
## Testmerges:
[#1797: 'More Sabre fixes' by covertcorvid at commit 7c9f2783b7](https://github.com/BeeStation/NSV13/pull/1797)
[#1801: 'overmap borders are more seamless for AI, and for shooting' by Ikalpo at commit afefd54de5](https://github.com/BeeStation/NSV13/pull/1801)
[#1846: 'Fixes some bad reference stuff with player ships' by Bokkiewokkie at commit 03a92238c2](https://github.com/BeeStation/NSV13/pull/1846)
[#1829: 'Self Surgery' by BetaCentari at commit 3bc3af01d1](https://github.com/BeeStation/NSV13/pull/1829)
[#1861: 'Snake Class medium gunboat' by Vasily2013 at commit a35f0a5846](https://github.com/BeeStation/NSV13/pull/1861)
[#1869: 'Knpc node next_id supports lists' by DeltaFire15 at commit 8b59d33d06](https://github.com/BeeStation/NSV13/pull/1869)
[#1840: 'Race Specific Emotes' by BetaCentari at commit 1d251a83e9](https://github.com/BeeStation/NSV13/pull/1840)
[#1830: 'Felinids don't like getting wet, and pulling them by the tail makes them upset' by red031000 at commit 4c1e4cfe6d](https://github.com/BeeStation/NSV13/pull/1830)
[#1878: 'WIP - Wire Guided Torpedoes' by Karmic-Skink at commit 4879552311](https://github.com/BeeStation/NSV13/pull/1878)
[#1864: 'Removes NSV donator code' by covertcorvid at commit 4099bf77f1](https://github.com/BeeStation/NSV13/pull/1864)
[#1886: 'Implements spatial partitioning for physics collision detection' by TheFakeElon at commit 16734bd044](https://github.com/BeeStation/NSV13/pull/1886)
[#1876: 'Fixes Ammo Rack Control Console UI' by TheFakeElon at commit 71e7d50197](https://github.com/BeeStation/NSV13/pull/1876)
[#1848: 'Notoriety (aka NSV - Pulsar edition)' by DeltaFire15 at commit 7cb261214c](https://github.com/BeeStation/NSV13/pull/1848)
[#1890: 'Glock ammo crates give 5 mags instead of 1' by someone543 at commit 7155ba2592](https://github.com/BeeStation/NSV13/pull/1890)
[#1887: 'Ensmallens the starmap' by covertcorvid at commit f050e19658](https://github.com/BeeStation/NSV13/pull/1887)
[#1895: 'Removed Unknown Elevator Button on The Tycoon' by Bobbanz1 at commit 1259dee34f](https://github.com/BeeStation/NSV13/pull/1895)
[#1894: 'More multi-Z stuff' by covertcorvid at commit 7366b7acb0](https://github.com/BeeStation/NSV13/pull/1894)

## Reproduction:
Drive into the edge of the overmap (we were on the Atlas at the time), watch as the ship bounces, rather than looping to the other side of space. If it helps, we were doing a boarding mission.

**Comment by red031000** [comment] 2022-04-23 19:08
duplicate of #1870

**Closed** 2022-04-28 02:26 UTC
Labels: bug, duplicate
