### ISSUE TITLE
Windows become invisible when built by hand

### ISSUE THREAD

**Issue by Grabovvski** [BeeStation/NSV13#815] opened 2020-08-10 20:40 UTC
## Round ID:
Multiple rounds

## Testmerges:
----

## Reproduction:
Build a fulltile glass window, be it reinforced or not

**Comment by Corsaka** [comment] 2020-08-17 14:48
Also #784; building windows creates the unanchored version.

**Comment by francinum** [comment] 2020-09-15 22:07
Duplicate of #784

**Closed by francinum** 2020-09-15 22:07 UTC
Labels: bug
